-d /auto/fsi/zd227/timing_attacks/mcu_fpga/hw/gowin_proj/impl/gwsynthesis/gowin_proj.vg
-p GW1N-9C-LQFP144-6
-pn GW1N-LV9LQ144C6/I5
-cst /auto/fsi/zd227/timing_attacks/mcu_fpga/hw/gowin_proj/src/pin_assignments.cst
-cfg /auto/fsi/zd227/timing_attacks/mcu_fpga/hw/gowin_proj/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
